spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: HYUNHO
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect  # Hibernate 6.x에 맞는 다이얼렉트
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
